api_platform:
    title: Test case
    version: 1.0.0
    formats:
        json: [ 'application/json' ]
    defaults:
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        stateless: false
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
